### ISSUE TITLE
请问iOS,Android项目如何运行?

### ISSUE THREAD

**Issue by buoge** [zwwill/yanxuan-weex-demo#1]
请问iOS,Android项目如何运行?

**Comment by zwwill** [comment]
抱歉今天才看到此问题：
ios打包需要开发者帐号，如果不是付费用户就只能通过xcode调试的方式安装在自己的关联手机上（就是手机需要使用此帐号登录）或者虚拟机调试。
步骤如下：
1、安装ios框架
```
$ weexpack platform add ios 
```
2、执行打包命令
```
$ weex build ios
```
![](https://user-images.githubusercontent.com/20720117/30237935-3e953126-956f-11e7-8196-c349d8939b02.png)
【注意】
运行到此处时，需要注意，如果你有开发者帐号可以继续按导航执行，如果没有就直接``Control + c``终止掉，此时bundle包已经导入到ios框架里了
![](https://user-images.githubusercontent.com/20720117/30237939-6bf05b28-956f-11e7-8789-55289f70697e.png)
3、xcode安装调试
具体操作可参考此文https://segmentfault.com/a/1190000010984857#articleHeader14
可以关注此文https://segmentfault.com/a/1190000011027225
预计周3将更新详细打包调试部分
