### ISSUE TITLE
编译完，页面有错误：Cannot read property 'matched' of undefined

### ISSUE THREAD

**Issue by huangzh123** [zwwill/yanxuan-weex-demo#12]
![qq 20171013111441](https://user-images.githubusercontent.com/8130494/31528739-c9d91df8-b007-11e7-8fa1-e0606e628ef3.png)
Cannot find element: #root
Cannot read property 'matched' of undefined

**Comment by huangzh123** [comment]
Cannot find element: #root
Cannot read property 'matched' of undefined

**Comment by relzhong** [comment]
@huangzh123 Can you find a solution?

**Comment by zwwill** [comment]
https://github.com/zwwill/yanxuan-weex-demo/pull/21
The problem has been solved
