### ISSUE TITLE
weexpack platform add android打包发现是weex官方demo

### ISSUE THREAD

**Issue by shadowZs** [zwwill/yanxuan-weex-demo#13]
weexpack platform add android打包发现是weex官方demo，另请问weex二维码是如何生成的

**Comment by zwwill** [comment]
@shadowZs 对，是官方的 demo 框架，并不是 weex 的主要维护对象，所以会存在或多或少的问题，会原生的同学可以自行改动。
另外你说的 weex 二维码是指 readme 中的吗？那个啥我打出的 jsbundle 然后放到服务器上生成的二维码

**Comment by shadowZs** [comment]
好的，谢谢
