### ISSUE TITLE
android 点击跳转后出现 Cannot find element: true

### ISSUE THREAD

**Issue by denept** [zwwill/yanxuan-weex-demo#14]
Cannot find element: true

**Comment by zwwill** [comment]
是点击 tab 切换还是 navigation 跳转

**Comment by denept** [comment]
进入页面后点击里面的商品，查看详情是出现。web控制台有这个错误，android程序则一直显示等待图标。

**Comment by zwwill** [comment]
@denept web 端和 andriod 是存在这个问题，需要根据平台动态更改跳转地址，这个 demo 的 ios 端做完就忙起来了，还没更新
