### ISSUE TITLE
npm run dev 遇到错误

### ISSUE THREAD

**Issue by Woooop** [zwwill/yanxuan-weex-demo#16]
Build Failed!
[webpack errors]

Vue packages version mismatch:

- vue@2.5.2
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest

**Comment by Woooop** [comment]
一般的方法都试了 都不行~

**Comment by zwwill** [comment]
更新一下你的 weex-toolkit

**Comment by yuzai** [comment]
我也遇到了这个问题，我的版本如下：
```
weex -v
   v1.1.0-beta.5
 - weexpack : v0.4.7-beta.11
 - weex-builder : v0.2.13-beta.2
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.5
```
这个weex的版本应该是很新了吧（昨天直接npm install -g weex-toolkit安装的），但是没有用，依然报这个错误。
我就用weex create新建了一个工程，将这个项目中的src以及assets中的内容拷贝到该项目中，并且修改webpack.config.js中的入口文件指向entry.js
可以正常运行，暂时没有发现什么差别

**Comment by zwwill** [comment]
前几周weexpack做了一次更新，后面就出现了兼容的问题，可以重新创建一个工厂，然后将源码资源copy过去可以勉强解决问题

**Comment by yuzai** [comment]
我把整理之后的放到一个[仓库](https://github.com/yuzai/weex-yanxuan)了，需要的话可以去看看，主要修改了webpack.config.js中的一些地方，同时把资源文件拷贝进去了

**Comment by Woooop** [comment]
@yuzai 我试试你的方法 谢谢~ 我的版本都是最新的

**Comment by zwwill** [comment]
https://github.com/zwwill/yanxuan-weex-demo/pull/20
The problem has been solved
