### ISSUE TITLE
debug时首页界面出不来

### ISSUE THREAD

**Issue by TonyLuo** [zwwill/yanxuan-weex-demo#17]
debug时用weex playground扫码，首页界面出不来，报[router-view] class not found的错误
在yanxuan-weex-demo/src下跑以下命令：
weex debug /Users/tony/dev/meiye/weex/yanxuan-weex-demo/src -e App.vue
或者sudo weex App.vue 都是出现下面的界面

![image](https://user-images.githubusercontent.com/3250305/32141918-041114ae-bc5a-11e7-92d4-1da0ba10d13f.png)

```

WXComponentFactory error type:[router-view] class not found
weex:[WXBridgeManager] callNative::callAddElement >>>> instanceId:73, ref:_root, dom:{"ref":"179","type":"div","attr":{"data-v-58cc0879":"","data-v-1529ae98":""},"style":{"position":"fixed","bottom":0,"left":0,"right":0,"height":90,"flexWrap":"nowrap","flexDirection":"row","justifyContent":"space-around","borderTopWidth":1,"borderTopColor":"#d9d9d9","backgroundColor":"#fafafa"}}, callback:
```

**Comment by mengyubo** [comment]
你是什么原因啊？我也遇到了这个问题，怎么解决的呢？
