### ISSUE TITLE
not bug, just a question. 使用了 vue-router 后，如何使用 weextoolkit 工具进行调试

### ISSUE THREAD

**Issue by xiyuanyuan** [zwwill/yanxuan-weex-demo#19]
如题

**Comment by zwwill** [comment]
不太好调试router的page，
可以用 weex debug 模式，调试整个工程

**Comment by lerit** [comment]
weex debug  src -e App.js 
我用这个启动整个项目调试，但是只有下面几个菜单，中间区域没有任何内容，调试发现this.$router为undefined
