### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by yfjl** [zwwill/yanxuan-weex-demo#2]
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'width' of null"

found in

---> <Indicator>
       <Slider>
         <YxSlider> at assets\components\YXSlider.vue
           <WeexDiv>
             <Scroller>
               <WeexDiv>
                 <Home> at assets\views\home.vue
                   <WeexDiv>
                     <Root>
warn @ vue.runtime.js:481
handleError @ vue.runtime.js:564
(anonymous) @ vue.runtime.js:705
nextTickHandler @ vue.runtime.js:650
Promise resolved (async)
timerFunc @ vue.runtime.js:665
queueNextTick @ vue.runtime.js:713
Vue.$nextTick @ vue.runtime.js:4091
render @ scroller.js:74
Vue._render @ vue.runtime.js:4119
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
Watcher @ vue.runtime.js:2868
mountComponent @ vue.runtime.js:2542
Vue$3.$mount @ vue.runtime.js:7388
init @ vue.runtime.js:3495
createComponent @ vue.runtime.js:5134
createElm @ vue.runtime.js:5077
createChildren @ vue.runtime.js:5205
createElm @ vue.runtime.js:5110
patch @ vue.runtime.js:5557
Vue._update @ vue.runtime.js:2414
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
Watcher @ vue.runtime.js:2868
mountComponent @ vue.runtime.js:2542
Vue$3.$mount @ vue.runtime.js:7388
init @ vue.runtime.js:3495
createComponent @ vue.runtime.js:5134
createElm @ vue.runtime.js:5077
patch @ vue.runtime.js:5557
Vue._update @ vue.runtime.js:2414
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
Watcher @ vue.runtime.js:2868
mountComponent @ vue.runtime.js:2542
Vue$3.$mount @ vue.runtime.js:7388
init @ vue.runtime.js:3495
createComponent @ vue.runtime.js:5134
createElm @ vue.runtime.js:5077
createChildren @ vue.runtime.js:5205
createElm @ vue.runtime.js:5110
patch @ vue.runtime.js:5557
Vue._update @ vue.runtime.js:2414
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
Watcher @ vue.runtime.js:2868
mountComponent @ vue.runtime.js:2542
Vue$3.$mount @ vue.runtime.js:7388
init @ vue.runtime.js:3495
createComponent @ vue.runtime.js:5134
createElm @ vue.runtime.js:5077
patch @ vue.runtime.js:5557
Vue._update @ vue.runtime.js:2414
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
Watcher @ vue.runtime.js:2868
mountComponent @ vue.runtime.js:2542
Vue$3.$mount @ vue.runtime.js:7388
init @ vue.runtime.js:3495
createComponent @ vue.runtime.js:5134
createElm @ vue.runtime.js:5077
updateChildren @ vue.runtime.js:5357
patchVnode @ vue.runtime.js:5432
patch @ vue.runtime.js:5562
Vue._update @ vue.runtime.js:2424
updateComponent @ vue.runtime.js:2538
get @ vue.runtime.js:2879
run @ vue.runtime.js:2956
flushSchedulerQueue @ vue.runtime.js:2724
(anonymous) @ vue.runtime.js:703
nextTickHandler @ vue.runtime.js:650
Promise resolved (async)
timerFunc @ vue.runtime.js:665
queueNextTick @ vue.runtime.js:713
f @ index.web.js:3
S.registerModule @ index.web.js:8
e.sync @ index.web.js:3
(anonymous) @ index.web.js:13
e @ index.web.js:3
(anonymous) @ index.web.js:3
(anonymous) @ index.web.js:3
vue.runtime.js:568 TypeError: Cannot read property 'width' of null
    at indicator.js:95
    at Array.reduce (<anonymous>)
    at _getVirtualRect (indicator.js:93)
    at Proxy.<anonymous> (indicator.js:79)
    at Array.<anonymous> (vue.runtime.js:703)
    at nextTickHandler (vue.runtime.js:650)
    at <anonymous>

**Comment by zwwill** [comment]
抱歉，今天才看到issues
由于时间问题，demo只进行了iOS的优化，
此问题正在跟进，是官方<indicator>的坑，不影响使用，后期将进行优化
