### ISSUE TITLE
能简单介绍一下部署流程吗

### ISSUE THREAD

**Issue by lijicheng123** [zwwill/yanxuan-weex-demo#23]
刚刚接触weex，想问问部署流程
一、web工程打包和app工程打包有什么区别？
```
npm run build (webpack)
```
能否理解为web工程打包是给普通的浏览器用的，nginx应该指向web目录下的index.html。

那么app打包是怎么回事呢？
是生成一个apk或者ios安装包，还是什么呢？
如果我做的是app嵌入页面（我们有原生开发团队），我应该把web打包的链接给app让他们嵌入还是怎么处理？

不知作者能否回答一下

**Comment by zwwill** [comment]
weexpack 打出的包三端都是一样的，只不过不一样的是执行的时候在什么地方执行，原生端有自己的 JSFramework ，生成 VNode进行解析，不同端的解析方式不同。具体的你可以看下这里
 https://segmentfault.com/a/1190000011027225

**Comment by lijicheng123** [comment]
1、web打包：
```
weexpack build web
```
然后将 ```` web/index.html ```
```
<script src="../node_modules/vue/dist/vue.runtime.js"></script>
    <script src="../node_modules/weex-vue-render/dist/index.js"></script>
```

```
```
<script src="../node_modules/vue/dist/vue.runtime.min.js"></script>
    <script src="../node_modules/weex-vue-render/dist/index.min.js"></script>
```
```
访问的是
``` web/index.html ```

2、app打包 
```  weexpack build ios  ```
```  weexpack build android  ```
是用来打包安装包的（比如安卓的apk），也就是说这命令是web前端开发不懂原生开发而用来生成app的。

3、如果我们有原生开发团队，对于要嵌入的页面，我们给的地址应该是
 ``` web/index.html ```
然后让他们集成weexsdk就行了

不知以上我理解的对不对
