### ISSUE TITLE
IOS模拟器上报错了

### ISSUE THREAD

**Issue by yinshipeng** [zwwill/yanxuan-weex-demo#24]
![image](http://ow3sf64ph.bkt.clouddn.com/17-11-15/88670946.jpg)

**Comment by zwwill** [comment]
报错信息是什么？

**Comment by Ttou** [comment]
同样的问题，playground跑是好的

**Comment by zwwill** [comment]
现在应该没问题了吧。你可以试一下，我自己跑是没问题的。

**Comment by LeeDung** [comment]
@yinshipeng @Ttou 这个问题解决了没？

**Comment by Ttou** [comment]
@LeeDung 模拟器是上是没问题了

**Comment by LeeDung** [comment]
@Ttou 怎么解决的？还记得不

**Comment by Ttou** [comment]
@LeeDung 看作者的提交记录 改webpack配置文件
