### ISSUE TITLE
同问。。切换到项目更目录 sudo npm install 后 执行 ./start 浏览器出来的页面是空白

### ISSUE THREAD

**Issue by yfming93** [zwwill/yanxuan-weex-demo#3]
同问。。Mac端切换到项目根目录 sudo npm install 后 执行 ./start 浏览器出来的（http://localhost:8080/web/index.html）
页面是空白。其他人的几个demo配置好环境后都是这两步就可打开 web预览。。在别人的demo中 执行 ./start 后 浏览器弹出 （http://localhost:12580/）
有预览效果。还望写个readme简单介绍下。感谢了。

**Comment by yfming93** [comment]
问题已解决。。Mac 端 sudo npm install  后。自己在项目根目录新建 platforms 文件夹。执行 weexpack platform add ios 添加iOS工程。pod install 后运行iOS工程 会报错 WEEX 'ATSDK/ATManager.h' file not found，此时 修改 Podfile 中ATSDK-Weex 为ATSD重新 pod install。

 然后返回项目根目录 npm run build 会在项目根目录创建 dist 文件夹。然后 找到里面的 index.js 复制替换到 /platforms/ios/bundlejs/index.js中。。再回头运行iOS工程就可以出现readme图片效果。昨天才接触 weex 。话说weex官方文档也是个坑。。望楼主后期分享知识的同时简单搞个readme介绍下，那样许多新手会感激涕淋。。🙄

**Comment by zwwill** [comment]
抱歉今天才看到issues提示，让你走了这么多弯路
具体运行步骤你可以参考此文
https://segmentfault.com/a/1190000010984857
