### ISSUE TITLE
webview不能访问

### ISSUE THREAD

**Issue by shophome** [zwwill/yanxuan-weex-demo#30]
http://192.168.1.6:8080/web/index.html?page=page/webview.js?weburl=http://www.baidu.com
没有响应

**Comment by zwwill** [comment]
目前 vue-router 和 navigator 一起用在 H5 模式还是有些冲突的。

**Comment by ZeiyThink** [comment]
这也是单页面不能在web 里显示的原因是吗？http://192.168.175.2:8080/web/?page=/dist/page/webview.js
白屏 什么都不显示
