### ISSUE TITLE
样式加载异常

### ISSUE THREAD

**Issue by Rem486** [zwwill/yanxuan-weex-demo#32]
![image](https://user-images.githubusercontent.com/22462424/33477710-a1ac545e-d6c1-11e7-9435-fd3b7ee0a775.png)

代码版本为目前最新，11月27日 下午6：42

每次第一次进入页面的时候，部分页面会有样式加载异常（样式渲染异常）的情况，可能是购物车、我的页面。

readme页面扫码加载的页面没有这个问题。代码好像有差异，帮忙瞅瞅，谢谢啦。

另外想请教一下，打包过后的index.web.js 特别大，3.+M  这个有什么办法处理一下那

**Comment by zwwill** [comment]
你是指 H5 还是 native ？H5 是会有几率出现这个问题。

**Comment by zwwill** [comment]
@Rem486 刚刚查了一下代码，发现 my.vue 使用的 header 组件出现重命名情况
```
components: {
            'header4': Header4
}
```
此组件在 shop.vue 中已经使用，所有改成可解决此问题。
```
components: {
            'header5': Header4
}
```

但这种解决方案优点太无奈，本身 my.vue page中就不应该有 header，如果不加 h5 页面显示像素计算就会失败。

**Comment by Rem486** [comment]
谢谢！原来命名会有这个影响，看demo的时候就好奇为什么这样命名O(∩_∩)O哈！

目前主要是用作h5微站。经常遇见**样式不加载** (像素计算) 的问题，“在使用了vue-router的页面就会有样式不加载的情况”，现在不是很了解渲染具体是怎么实现的，只是发现好像使用组件的方式引入进来会成功渲染。。。。
https://github.com/weexteam/weex-toolkit/issues/200

**Comment by erha19** [comment]
@Rem486 I see, that's a very strange rendering mechanism, maybe you can join in the [mail list of weex](http://mail-archives.apache.org/mod_mbox/incubator-weex-dev/) to discuss this issue, I will help you to promote the solution of this problem.
