### ISSUE TITLE
Module Build faild：SyntaxError:Unexpected token,expected,(8:12)

### ISSUE THREAD

**Issue by alexfeng** [zwwill/yanxuan-weex-demo#35]
运行 npm run build 时报这样的语法错误，看问题好像是这里的isIpx&&isIpx()
=======================
  ERROR in ./src/mixins/index.js
    Module build failed: SyntaxError: Unexpected token, expected , (8:12)

       6 |       }
       7 |     },
    >  8 |       isIpx&&isIpx() {
         |             ^
       9 |           return weex && (weex.config.env.deviceModel === 'iPhone10,3' || weex.config.env.deviceModel === 'iPhone10,6');
      10 |       }
      11 |   }

     @ ./src/entry.js 15:14-33
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! yanxuan-weex@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the yanxuan-weex@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by zwwill** [comment]
感谢提醒，今天修复了一个问题，替换多了。。
