### ISSUE TITLE
weex -> weex传参

### ISSUE THREAD

**Issue by pcwang0205** [zwwill/yanxuan-weex-demo#38]
navigator.push传参有什么比较好的方式吗？

**Comment by zwwill** [comment]
可再 push 的 options.url 上添加一些参数，在下一个页面的 weex.config.bundleUrl 中读取

**Comment by pcwang0205** [comment]
这种方式只适合本地weex吧？如果远程weex貌似不行吧？

**Comment by pcwang0205** [comment]
这种方式只适合本地weex吧？如果远程weex貌似不行吧？

**Comment by pcwang0205** [comment]
只适合用file:///xxxxxxxx.js?userid=xxx这种可以，
如果是https://xxxxxxxxxxxxxxxx.js?userid=xx，这种取不到吧

**Comment by zwwill** [comment]
可以，需要你自己做判断。
