### ISSUE TITLE
在ios上运行出现屏幕不全的问题

### ISSUE THREAD

**Issue by pluslicy** [zwwill/yanxuan-weex-demo#39]
你好，在ios上调试时，页面在iphone上显示不全，导航条下面还留出来一部分没有被页面渲染，您是否遇到过类似问题？

**Comment by zwwill** [comment]
https://segmentfault.com/q/1010000010878798
here

**Comment by pluslicy** [comment]
万分感谢！！

祝工作顺利！


		致
礼!
		李春雨
