### ISSUE TITLE
项目在浏览器里运行，全屏显示时，click事件无效，以手机页面显示时，click事件有效果

### ISSUE THREAD

**Issue by xiaoliangsu** [zwwill/yanxuan-weex-demo#40]
在playground用手机显示时以及浏览器以手机模式显示时，click是正常的，但是在浏览器里面全屏时候的click无效，测试了chrom  火狐 safiri 均无效。

**Comment by zwwill** [comment]
h5 模式下的click事件注册其实是注册给了 touchstart ，在非手机模式下触发不到 touch 事件所以没有效果

**Comment by xiaoliangsu** [comment]
那您说的意思是 weex写的项目是不支持web端么？

**Comment by zwwill** [comment]
一般来说，使用场景都是手机上，pc上很少出现
