### ISSUE TITLE
iOS 工程里的内容怎么被移掉了？

### ISSUE THREAD

**Issue by ErHu1993** [zwwill/yanxuan-weex-demo#42]

**Comment by zwwill** [comment]
是的。避免大家在使用的时候出现冲突

**Comment by sch1111878** [comment]
针对我当前的版本需要处理的问题:(仅针对iOS)
1.下载下来首先需要 npm install
2.根目录下的 ios.config.json 把AppId补全,不然你打包时没有bundle id 无法安装
3.ios项目不完全,作者的.gitignore 应该设置的有问题 重新初始化  weexpack platform add ios
4.然后又提示plugins 目录有问题,在这个目录下新建文件 plugins.json,内容如下
{
  "ios": [],
  "web": [],
  "android": []
}
5.然后package.json 中最好再增加几个脚本(在 scripts 下)
    "ios": "weex run ios"
经过这些已经能运行了
