### ISSUE TITLE
？？web组建指向网易，等于高仿？？？

### ISSUE THREAD

**Issue by sanriqing** [zwwill/yanxuan-weex-demo#43]
请问现在的这个是全部的源码吗。、。是的话有些过分咯兄弟。。。

**Comment by zwwill** [comment]
web模块只是对web控件对使用，weex组件对是其他部分，全部都实现就有些多余了。
是不是说高仿部分比较准确？

**Comment by sanriqing** [comment]
好吧，可能只是和我预期想的比比较大的区别吧
