### ISSUE TITLE
请问您的这个项目，h5点击跳转失败

### ISSUE THREAD

**Issue by baneyue** [zwwill/yanxuan-weex-demo#44]
# 一句话概括
1、如题，H5子页面跳转失败，路径指向不正确，希望解决下，thks
2、如何做h5的多屏适配？
3、怎样彻底掌握整个项目结构的配置？

# 详细描述

# 重现（选）

**Comment by zwwill** [comment]
逐一回答：
1、由于使用了weex的分包bundle和vue-router，导致项目有些冲突，后面试图修复
2、h5多屏适配可以根据navigator进行适配
3、项目的配置一半是weexpack提供的，此处在此基础上做了部分改动，语法为webpack语法

**Comment by baneyue** [comment]
多谢多谢
