### ISSUE TITLE
请大咖解惑： webview.js与index.js包文件是如何被native app识别和调用

### ISSUE THREAD

**Issue by ZhangBo2016** [zwwill/yanxuan-weex-demo#45]
# 一句话概括
如题，看了源码，不明白webview.vue打包的webview.js使如何被native调用，以及weex.config.bundleURL是否就是index.js的引用。
# 详细描述
在weex官网hackernews中，只生成了index.js包文件，这比较容易理解。但是看到yanxuan这个demo后，很不明白对于webview.js如何被native app识别和调用。

希望大咖解答下，万分感谢
# 重现（选）

**Comment by sumincy** [comment]
集成到原生app里面不要用到webconfig.js 这些了  vue界面这些 都打包成js bundle了   由对应平台的WeexSDK去解析这些jsbundle 渲染ui。

**Comment by zwwill** [comment]
@ZhangBo2016  可以看下这篇文章 https://github.com/zwwill/blog/issues/3

**Comment by ZhangBo2016** [comment]
我理解是，起初native加载包文件 webview.js，随后执行webview控件，加载包文件 index.js（此为也没展示的所有内容）。

**但是有一点想不通，webview.js是如何在native被执行的,  是否需要更改config配置？**

谢谢回答下@zwwill

**Comment by ZhangBo2016** [comment]
我理解是，起初weex运行包文件 webview.js， 然后native在webview组件中加载 index.js (此为yuanxuan首页内容的包文件)。

如果是这个逻辑的话，有一点不明白，是否需要改config配置，weex才会运行webview.js。否则weex默认运行的是 index.js吧

请@zwwill 解答, 谢谢了。

**Comment by zwwill** [comment]
此demo有两页，第一页是首页，是单页面，有5个tab子页，第二页是web页，内置web组件（即webview）加载普通h5网页。两者都是原生绘制的也没，页面的跳转事件大致是这样【UI作出响应】->【通过bridge层通知js runtime 层】->【js解析命令做跳转通知】->【由bridge层通知原生层做新页面开启】->【加载对于页面的js bundle 解析绘制原生UI 绑定事件等操作】
