### ISSUE TITLE
老师，关于icon 图片的使用

### ISSUE THREAD

**Issue by sumincy** [zwwill/yanxuan-weex-demo#46]
初学vue  weex
不清楚您demo 中  header  tab-bar 组件中 
那些  <text class="bar-ic iconfont" :style="testCS">&#xe660;</text>
中的
&#xe660; 是怎么对应到图片的

**Comment by sumincy** [comment]
&   #xe660 ;

**Comment by sumincy** [comment]
类似这些

**Comment by zwwill** [comment]
是iconfont 字体中的 Unicode模式

**Comment by sumincy** [comment]
@zwwill  谢谢 我去了解下

**Comment by zwwill** [comment]
@sumincy 不客气

**Comment by Hideer** [comment]
您是使用在线连接还是将字体下载下来后使用呢，我在使用的时候web端字体能够正常显示，但是手机上无法使用

**Comment by zwwill** [comment]
@Hideer 再现字体是可以直接使用的，本地的需要处理下。将你的使用方式贴一下看看

**Comment by Hideer** [comment]
```
<style  scoped>
    @font-face {
        font-family: 'iconfont';  /* project id 576400 */
        src: url('//at.alicdn.com/t/font_576400_7s705s2cj960f6r.eot');
        src: url('//at.alicdn.com/t/font_576400_7s705s2cj960f6r.eot?#iefix') format('embedded-opentype'),
        url('//at.alicdn.com/t/font_576400_7s705s2cj960f6r.woff') format('woff'),
        url('//at.alicdn.com/t/font_576400_7s705s2cj960f6r.ttf') format('truetype'),
        url('//at.alicdn.com/t/font_576400_7s705s2cj960f6r.svg#iconfont') format('svg');
    }
    .iconfont {
        font-family:iconfont;
    }
```
目前就是简单的写在组件中的style样式中

**Comment by zwwill** [comment]
使用姿势不对
https://weex.apache.org/cn/references/components/text.html#zi-ding-yi-zi-ti

**Comment by Hideer** [comment]
官方的自定义字体同样的显示不出来额。。

**Comment by zwwill** [comment]
http://dotwe.org/vue/16a035d66347da2ba71e624aca61457f

**Comment by sumincy** [comment]
@Hideer  //at.alicdn.com/t/font_576400_7s705s2cj960f6r.ttf     配置这个就有效果了

**Comment by Hideer** [comment]
嗯呢，谢谢，iconfont这个问题，我解决了，请问您也是在开发weex应用吗，方便加个微信交流么

**Comment by CodeDreamfy** [comment]
提一点， 如果使用 动态的icon 赋值显示的话 需要换成`\uexxx`的形式，或者使用decode
