### ISSUE TITLE
安卓端出现weex默认导航条

### ISSUE THREAD

**Issue by cheesekun** [zwwill/yanxuan-weex-demo#47]
web端的话显示正常
但是安卓端就出现了官方的导航条
![_20180122163416](https://user-images.githubusercontent.com/21058528/35211604-246cec3e-ff92-11e7-99c3-dcf497817e9d.jpg)

**Comment by zwwill** [comment]
嗯，之前也有人反应过，应该是官方提供等platform 做了更新默认带上了navigationbar，在源码里清理掉即可。

**Comment by cheesekun** [comment]
然而不知道清理哪里。谷歌一下午，有几个人也问了这个问题，没有查到解决方法。
或者降级weex吧，大佬你之前的weex-toolkit版本是多少

**Comment by zwwill** [comment]
- weexpack : v0.4.7-beta.8
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.3.1
 - weex-previewer : v1.3.13-beta.3

**Comment by cheesekun** [comment]
用了你的版本后，导航栏还在，但是之前遇到的坑不见了。先谢谢一波大佬。

**Comment by zwwill** [comment]
找个会android 的小伙伴帮你吧plantform 的导航头去掉就好了，综合来看，weex还是需要原生同学支持才行。不然效率和细节都没法优化

**Comment by cheesekun** [comment]
嗯，我老大也说之后给安卓的小伙伴看看。这几天初学weex，windows下遇到太多坑，跟着文档都会出错。
官方demo不更新，网上的demo也少。对初学者真的很不友好。 只能慢慢踩坑了。
这个issue就关掉吧。谢谢大佬了。

**Comment by zwwill** [comment]
官方文档即将更新，上次weexconf我们已经规划了weex的社区发展

**Comment by cheesekun** [comment]
十分期待更新文档。我使用最新的脚手架，使用`navigator`出现了莫名其妙的错误，用的还都是官方文档的demo。。。吊诡的是，回退`weexpack`版本，居然就能用了。。
希望文档能像`vue`那般详尽，那就太好了。感谢开源。

**Comment by cheesekun** [comment]
![4276669995-5a6882ac149db_articlex](https://user-images.githubusercontent.com/21058528/35423324-2590d17c-0288-11e8-8f17-4506b40fc4c2.png)
在`AndroidManifest.xml 文件`上添加这一段就可以解决。
