### ISSUE TITLE
不能执行add platform命令

### ISSUE THREAD

**Issue by romantictravel** [zwwill/yanxuan-weex-demo#5]
E:\h5\yanxuan-weex-demo>weex platform add android
Error: Current working directory is not a weexpack project.

**Comment by zwwill** [comment]
需要安装基础的执行环境
```
$ npm install -g weex-toolkit
$ npm install -g weexpack
```
https://segmentfault.com/a/1190000010984857

**Comment by auven** [comment]
我这两个都装了，还是报这个错误：
```bash
Error: Current working directory is not a weexpack project.
```
然后我对比了一下其他weex项目，发现少了`platforms`这个文件夹，于是我抱着试试看的想法，在根目录下添加了`platforms`文件夹，然后重新运行`weex platform add android`，居然成功了！！！

思考：是不是weex的脚手架的缺陷？没有`platforms`就无法识别为一个weex项目？

**总结：解决办法是，在根目录下添加`platforms`文件夹。**

**Comment by zwwill** [comment]
这个锅是我的问题，我在push代码是忽略了这个文件夹，感谢提醒，现在加回去
