### ISSUE TITLE
npm run serve后，打不开网页

### ISSUE THREAD

**Issue by xuzhenhao** [zwwill/yanxuan-weex-demo#50]
# 一句话概括
npm run serve后，打不开网页
# 详细描述
npm run serve成功后，在浏览器上无法浏览，显示无法连接到服务器。iOS端是正常的。用weex初始化的空项目正常。不知是不是webpack的配置有问题
# 重现（选）

**Comment by zwwill** [comment]
运行试试
```
$ weex run web
```

**Comment by xuzhenhao** [comment]
还是不行。暂时用weex debug src指令看的，影响也不大。感谢回复。
