### ISSUE TITLE
配置路由之后无法打开index.html  页面进行调试

### ISSUE THREAD

**Issue by James-dai** [zwwill/yanxuan-weex-demo#51]
# 一句话概括

配置路由之后无法打开index.html  页面进行调试

# 详细描述
在掘金上面看到你这篇文章写的很不错，
https://juejin.im/entry/59af918c5188251240635a96
也是在学习中，项目可以跑起来，但是无法用weexplayground进行调试啊。
能根据现在master分支，说一下怎么进行整个项目的调试吗？

# 重现（选）

**Comment by zwwill** [comment]
```
$ weex debug src -e entry.js
```
使用weex debug 指令
https://weex.apache.org/cn/tools/toolkit.html#debug

**Comment by James-dai** [comment]
恩，h5版本的页面是可以启动起来的。但是我调试的时候如何用weexplayground 扫描h5页面去debugger呢？

1、启动项目：npm run dev & npm run serve 
2、开启调试：weex debug -e entry.js

我用weexplayground 扫描http://192.168.68.37:8080/web/#/home 这个页面。会报错。
如何进行页面调试呢？


![debugger1](https://user-images.githubusercontent.com/4067081/36624380-7464e45a-1949-11e8-80c9-4e443ca079be.jpg)
![debugger2](https://user-images.githubusercontent.com/4067081/36624382-74f420ac-1949-11e8-80be-bb19f997a9ab.jpg)
![debugger3](https://user-images.githubusercontent.com/4067081/36624383-752f6ec8-1949-11e8-8787-30a29f856e95.jpg)
![debugger4](https://user-images.githubusercontent.com/4067081/36624384-757ca468-1949-11e8-825e-c6b0bf836777.jpg)

**Comment by James-dai** [comment]
@zwwill

**Comment by zwwill** [comment]
直接执行 weex debug -e entry.js 即可调试，不需要执行 npm run dev & npm run serve 
另外，你的 devtool 是新版本，我用的是0.3.3，不知道是否是因为不支持了

**Comment by James-dai** [comment]
@zwwill 
项目起来之后，我用devtool 扫描 二维码进入之后并不能跳转到h5页面。依旧会跳回打开app时候默认的首页。
如果你这边方便的话，可以用最新的工具调试一下master 分支的代码😯~~~
还是说我哪一步操作有问题？

![Uploading debugger2.jpg…]()
![Uploading debugger5.jpg…]()
![Uploading debugger6.jpg…]()

**Comment by James-dai** [comment]
@zwwill 
![debugger2](https://user-images.githubusercontent.com/4067081/36624651-bda8ac3e-194c-11e8-81b6-6245691bcd49.jpg)
![Uploading debugger5.jpg…]()
![Uploading debugger6.jpg…]()

**Comment by zwwill** [comment]
第一个二维码是用来建立手机和本地服务的联系的，是一种映射关系，后面你需要使用手机扫码真正需求调试的页面，就可以进行调试了，这个可能是官方做的一次修改，之前是两个二维码，还会有一个项目二维码。

**Comment by James-dai** [comment]
@zwwill 
我明白，
第一个二维码是用来建立手机和本地服务的联系的，是一种映射关系
因为官网的项目是会有一个preview.html 页面会自动生成一个调试页面的二维码。
我想问的就是第二个二维码在你的项目中是如何打开被查看。
你假如了vue-router，所以访问 preview.html 页面都会被重定向到 /web/home 的路径~

**Comment by James-dai** [comment]
@zwwill 
ok ，我自己找到问题了。
用weexplayground 扫描 ，npm run build 打包出来的文件路径：http://192.168.0.102:8080/dist/index.js
就可以在调试工具里面显示啦。
还在学习中，感谢你的开源项目！非常棒！！
![debugger8](https://user-images.githubusercontent.com/4067081/36631734-34026f4e-19b8-11e8-9248-c30fce3f4062.jpg)
![debugger9](https://user-images.githubusercontent.com/4067081/36631735-344bb05a-19b8-11e8-8793-8ff7428fcf3b.jpg)
