### ISSUE TITLE
项目怎么跑不起来了呢？Cannot GET /web/

### ISSUE THREAD

**Issue by codeliu6572** [zwwill/yanxuan-weex-demo#54]
我前几天下载的当时还能跑，今天又下载跑起来之后空白页面：Cannot GET /web/ 而且Xcode一跑就闪退，不是崩溃，是Xcode闪退，反复试过了，每次都闪退.
npm install的时候警告：npm WARN yanxuan-weex@1.0.0 No repository field.
少了个配置？看到文件是一天前更新过，但是很奇怪，别人那里可以，我这里不可以，不知道是不是因为环境的版本的问题npm5.5.1的，还请告知原因。

**Comment by codeliu6572** [comment]
@erha19 @zwwill

**Comment by sapphirezzz** [comment]
我也是，跑Xcode，编译完还没install到模拟器，Xcode就闪退。必现。
@zwwill

**Comment by zwwill** [comment]
@sapphirezzz  使用weex build 命令打包 bundle，在出现引导输入 id 时退出，接着使用xcode编辑器进行安装
