### ISSUE TITLE
关于项目的启功

### ISSUE THREAD

**Issue by 15826954460** [zwwill/yanxuan-weex-demo#57]
# 一句话概括
请问一下大神，download 你的项目在window环境下跑起来，运行 npm install 后，再执行 npm run dev & npm run serve  项目跑步起来，是不是要 先配置 android 环境啊！
希望可以得到您的解惑，谢谢
# 详细描述

# 重现（选）

**Comment by zwwill** [comment]
你这样执行的是H5的页面，要想执行android 的打包，可以使用 `weex run android`，运行之前需要安装下android 的platform `weex platform add android `
