### ISSUE TITLE
vue-router写tabbar时遇到style不能及时渲染

### ISSUE THREAD

**Issue by wilson-0422** [zwwill/yanxuan-weex-demo#58]
# 模仿严选的tabbar 但是不能及时渲染home页面的style，用的最新的weexmo'ban

# # 通过模仿严选的tabbar 但是发现所有vue-router 的页面都无法正常显示style，px不编译，初始页面干脆style里面的样式都不执行。似乎像页面渲染没有渲染。但是切换一下回home的时候样式又出现了
![image](https://user-images.githubusercontent.com/26596057/36967618-2efb288a-209b-11e8-808b-7d251238393d.png)
![image](https://user-images.githubusercontent.com/26596057/36967686-5b1a328a-209b-11e8-9543-ad7f55f493ff.png)
![image](https://user-images.githubusercontent.com/26596057/36968149-9e58d21c-209c-11e8-8117-a195b359cb8c.png)
![c265843f-6fef-4a0c-9ad6-15347c7d8f62](https://user-images.githubusercontent.com/26596057/36968237-f0847d84-209c-11e8-8589-3a51fcebb911.png)

但是其他非home的页面的样式，没有编译，px没有转换。

# 重现（选）

**Comment by 15826954460** [comment]
请问一下，你的项目启动的了，我按照作者的 npm install 之后 npm run dev  就直接报了一大堆错误，想问一下你是如何启动项目的，然后都配置了些啥，初次了解 weex 但是对 vue 特别熟，希望可以互相学习

**Comment by wilson-0422** [comment]
我就是直接copy他的代码，运行的。。。没啥改变。可能你的环境没装好，去weex官网看看先
