### ISSUE TITLE
网页版样式异常，安卓版在虚拟机上运行异常

### ISSUE THREAD

**Issue by auven** [zwwill/yanxuan-weex-demo#6]
**开发环境**：
win10 64位，安卓虚拟机是`AVD Manager`

### 网页版样式显示异常
<div align=center>
<img width="158" alt="chrome_2017-09-13_09-47-54" src="https://user-images.githubusercontent.com/23731087/30356036-897f5eb2-9869-11e7-8e60-1d96c54fe61e.png">

<img width="158" alt="chrome_2017-09-13_09-47-54" src="https://user-images.githubusercontent.com/23731087/30356052-9adca700-9869-11e7-8fff-ed6a1076c7d7.gif">
</div>

### 安卓版虚拟机上运行异常
安卓版在**虚拟机**上运行**切换底部tab**会出现`Unfortunately, YanXuanWeex has stopped`
<div align=center>
<img width="232" alt="qemu-system-x86_64_2017-09-13_09-46-11" src="https://user-images.githubusercontent.com/23731087/30356137-f3c3a1d4-9869-11e7-81d5-e6260f140486.png">
<img width="231" alt="qemu-system-x86_64_2017-09-13_09-46-19" src="https://user-images.githubusercontent.com/23731087/30356145-fa46caae-9869-11e7-8b67-05fe03a87cb0.png">
</div>

**Comment by zwwill** [comment]
tab切换是使用vue-router实现的，tab单页由于使用了固定布局，会出现这种问题，导致崩溃，目前暂未优化android版本。
至于web的问题，不知道你的代码是什么时候pull下来的，建议你使用最新的代码试试。
官方的``<indicator/>``存在问题，但不应该阻塞runtime的样式出现计算。

**Comment by auven** [comment]
我的代码是最新的，错误提示如图：

<div align="center">
<img width="538" alt="chrome_2017-09-13_13-02-53" src="https://user-images.githubusercontent.com/23731087/30360464-0ec97714-9884-11e7-85ff-6b6c99613ad3.png">
</div>

**Comment by zwwill** [comment]
是的，目前版本的``<indicator/>``组件是存在这个问题的

**Comment by Yuamo** [comment]
我也遇到同样问题。。。

**Comment by Kntt** [comment]
@zwwill 
老铁, 更新个android的包呗,  原生的是真不会, indicator可以更新weex-vue-render@0.12.14解决,

**Comment by zwwill** [comment]
感谢 @Kntt 提醒，已经更新至weex-vue-render@0.12.14
至于安卓包，由于最近在用weex写游戏，加上公司项目赶紧，实在没时间维护，还请有余力的老铁们多push几把。

**Comment by Kntt** [comment]
最近看来下weex-vue-render的包， 发现好像要把各个module给分离出来， 出来weex-vue-dom，weex-vue-modal。。。等好多个包

**Comment by goodmanman** [comment]
怎么能热更新阿？大神阿。每次都是加载的npm run build ,npm run serve 在web 网页上

**Comment by akingyin1987** [comment]
问个问题，这是用什么 工具打开呢，我用AS打开根本没办法加载进来

**Comment by auven** [comment]
@akingyin1987  我是用 **AVD Manager**，可以去这个网站 `http://www.androiddevtools.cn`，下载SDK-tool，解压后里面就有AVD Manager
