### ISSUE TITLE
[请教]如何清空input的内容

### ISSUE THREAD

**Issue by dingly** [zwwill/yanxuan-weex-demo#60]
<template>
  <div>
     <input :value='form.value' @input='inputAction'></input>
     <text @click='reset'>清空input</text>
 </div>
</template>
<script>
  export default {
     data(){
         return {
           form: {value: ''}
         } 
    },

   methods: {
      inputAction(event){
            this.form.value = event.value;
     },
     reset(){
       this.form.value = ''; 
    }
   }
  }
</scrippt>

点击清空input时， input内容还是存在

**Comment by zwwill** [comment]
方法同vue 你可以看下文档https://weex.apache.org/cn/references/components/input.html#sidebar
