### ISSUE TITLE
page 里的页面怎么预览 

### ISSUE THREAD

**Issue by ZeiyThink** [zwwill/yanxuan-weex-demo#61]
# page 里的页面怎么预览 
http://192.168.175.2:8080/web/?page=/page/fareninfo.js   这样的连接打开也不报错，就是白屏什么都不显示

# 详细描述
在app里页面能正常显示，但是在浏览器里预览的时候什么都不显示，是什么原因呢，我试了，webview 打开也是白屏。打包都没什么错，就是web 里什么都不显示，求指导
# 重现（选）

**Comment by zwwill** [comment]
我的这个项目使用浏览器模式预览web模块是有些问题的。目前原生下是可以的
