### ISSUE TITLE
navigator 相关

### ISSUE THREAD

**Issue by asd8855** [zwwill/yanxuan-weex-demo#62]
两个问题
1.bundlejs文件夹中怎么设置可以生成多个js文件，我多个页面，dist中也是多个，但是bundlejs文件夹中只有一个index.js
2.navigator push 的url是哪里文件的地址，dist中对应文件的地址，还是bundlejs中相应文件的地址。

和您的项目无关，但请解答一下。

**Comment by zwwill** [comment]
1、看一下你的webpack配置文件是有更改，默认是单独打包所有的vue或we文件的。
2、可以是本地的也可以远程的地址，dist打包出来的知识暂时的文件，最后会被同步到构建好的app里。具体可以看下https://github.com/zwwill/yanxuan-weex-demo/blob/master/src/assets/util.js

**Comment by asd8855** [comment]
我用的是默认的用weex-toolkit 初始的项目，怎么修改webpack文件？

**Comment by zwwill** [comment]
一般在目录的 【webpack.config.js】文件
https://github.com/zwwill/yanxuan-weex-demo/blob/master/webpack.config.js

**Comment by zwwill** [comment]
有一个walk函数你研究下

**Comment by asd8855** [comment]
好的 谢谢大佬

**Comment by asd8855** [comment]
大佬，我的dist是正常的，可以把所有的文件进行打包处理。但是jsbundle中只有一个index.js 相当于一个入口文件，如何把dist中的js文件，导出到jsbundle文件夹中?

**Comment by asd8855** [comment]
至于和index.vue同级目录的文件，才会显示在bundlejs中，请问怎么设置才能让所有的问题都出现在bundlejs文件中

**Comment by zwwill** [comment]
![image](https://user-images.githubusercontent.com/20720117/37516244-764f69b6-2948-11e8-9d5a-ab0040f96497.png)
你是指platform下的bundlejs文件吗？
使用构建命令即可自动复制，如
```
$ weex build ios
```

**Comment by asd8855** [comment]
他这样也是只会把与index.vue 同级目录的vue文件导出到platfrom下的bundlejs中，如果与index.vue在同一级目录的是一个文件夹，它不会把文件夹中的vue文件导出到platfrom下的bundlejs中？这个该怎么解决？

**Comment by asd8855** [comment]
<img width="321" alt="weex" src="https://user-images.githubusercontent.com/20153584/37517024-29b20c5a-294b-11e8-894a-1aadcfed07ec.png">
例如这种

**Comment by asd8855** [comment]
但是bundlejs中只有一个index.js
<img width="599" alt="weex33" src="https://user-images.githubusercontent.com/20153584/37517178-86f55ae8-294b-11e8-8505-41d88597320e.png">

**Comment by asd8855** [comment]
您可以加下我QQ吗？820981594 被这个问题折磨好几天了

**Comment by zwwill** [comment]
看一下webpack.config.js 的 walk函数
![image](https://user-images.githubusercontent.com/20720117/37517265-ce1c11be-294b-11e8-82e2-b570566fd617.png)

**Comment by zwwill** [comment]
不用QQ，可以加微信

**Comment by asd8855** [comment]
asd-kk微信号





新浪邮箱客户端

------------------------原始邮件------------------------
发件人：木羽<notifications@github.com>
时间：2018年3月16日 19:00:13
收件人：zwwill/yanxuan-weex-demo<yanxuan-weex-demo@noreply.github.com>
抄送：asd13148866<asd13148866@sina.com>,Author<author@noreply.github.com>
主题：Re: [zwwill/yanxuan-weex-demo] navigator 相关 (#62)

不用QQ，可以加微信

**Comment by asd8855** [comment]
asd--kk微信号

**Comment by asd8855** [comment]
![wechatimg21](https://user-images.githubusercontent.com/20153584/37521432-b372d068-295b-11e8-92bb-ab8b65ad6733.jpeg)

**Comment by asd8855** [comment]
你红框的那块我看到了，我的dist文件夹中的文件是ok的，只不过从dist迁移到bundlejs中的时候只有index.js
