### ISSUE TITLE
关于weex开发三端代码的疑问

### ISSUE THREAD

**Issue by zhongdom** [zwwill/yanxuan-weex-demo#69]
- 此项目是三端代码，是以前端代码为标准开发，然后适配到iOS和android平台吗？采用这种方式是不是只能把素材资源都放到远端而不能放到本地了？
- 开发过程是怎样debug的？适配到iOS平台的时候又是怎样debug的？有使用`weex debug`工具吗？

**Comment by zwwill** [comment]
1、三端代码是同构的一任何一个平台做标志都可以，看习惯，可以用web也可以用ios，但最后都需要做三端的效果走查，保证一直，一遍做降级操作。
2、素材是需要放在远端的，一般做cdn加速。不过也可以用本地的，不过需要适配不同端的 uri的头，这样也不便做热更，所有建议远端
3、debug 单页模式使 weex debug 就可以了，如果有远程数据的话，最好是先mock在联调。
