### ISSUE TITLE
android 没搞吗 老铁

### ISSUE THREAD

**Issue by XiaoYiS** [zwwill/yanxuan-weex-demo#70]
# 一句话概括

# 详细描述

# 重现（选）

**Comment by XiaoYiS** [comment]
android platforms  没有吗，方便也搞一个？

**Comment by zwwill** [comment]
起初是以 ios 为基础做的，刚加上了 android 的platform，不过还有些问题，后续修复

**Comment by XiaoYiS** [comment]
我用的是安卓原生的跳转，所以在跳转上有一些问题，到时候你修复了 参考一下你的
