### ISSUE TITLE
富文本如何渲染， how to use rich text in weex

### ISSUE THREAD

**Issue by soldier9527** [zwwill/yanxuan-weex-demo#71]
# 一句话概括
富文本如何渲染
# 详细描述

我是新手，查阅了一些内容，如果我需要渲染富文本内容的话，有几种思路：

1. 正则替换文本内容为text，css内容也正则替换成正确的内容
2. web标签打开一个空页面，内部渲染富文本（我这写判断如果是web端，直接渲染，如果是app端就使用<web>吗）
3. 我看之前阿里巴巴维护的weex issue 里面说会增加 rich text 标签，但我没找到使用方法和是否实现了

 
我想了解下你们当初如何实现的,谢谢

# 重现（选）

**Comment by zwwill** [comment]
v-html 
需要原生同学扩展

**Comment by soldier9527** [comment]
哦，谢谢
