### ISSUE TITLE
Mac npm run dev报错

### ISSUE THREAD

**Issue by herozhou** [zwwill/yanxuan-weex-demo#8]
npm run build 没问题，但是运行npm run dev会报错

```
ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3754,4]

ERROR in App.web.js from UglifyJs
Unexpected token: name (urlParts) [App.web.js:3754,4]

ERROR in page/web.web.js from UglifyJs
Unexpected token: name (urlParts) [page/web.web.js:3754,4]

ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3756,4]

ERROR in App.web.js from UglifyJs
Unexpected token: name (urlParts) [App.web.js:3756,4]

ERROR in page/web.web.js from UglifyJs
Unexpected token: name (urlParts) [page/web.web.js:3756,4]
webpack: Failed to compile.


```

**Comment by zwwill** [comment]
不应该啊。

![image](https://user-images.githubusercontent.com/20720117/30601504-c0df94dc-9d94-11e7-95b8-3c547e413dad.png)

不知你的执行环境有没有安装完整

**Comment by herozhou** [comment]
是我描述错了，应该是npm run server的问题，npm run dev 是正常的。
但是npm run dev&npm run server时，就会收到如下报错
![image](https://user-images.githubusercontent.com/16045604/30621401-73f4330a-9ddd-11e7-834e-b27a231a06da.png)

![image](https://user-images.githubusercontent.com/16045604/30621467-d22ccd60-9ddd-11e7-9789-2701568e5b2f.png)

我看下这个文件在ios文件夹里，我只是在PC上运行，不至于跟ios有问题吧？
可能是webpack的版本问题？

**Comment by herozhou** [comment]
刚才运行一下又能出来了，虽然不知道为什么

**Comment by heuuLZP** [comment]
同样的问题，执行npm run serve会包上述错误，不知怎么解决

**Comment by heuuLZP** [comment]
又试了下windows平台

不支持 npm run dev & npm run serve 命令，需要分开执行
执行npm run serve也会报同样的错误

**Comment by TonyLuo** [comment]
MacOS 有同样的问题
ERROR in index.web.js from UglifyJs
Unexpected token: name (utilFunc) [index.web.js:2302,4]

ERROR in App.web.js from UglifyJs
Unexpected token: name (utilFunc) [App.web.js:2302,4]

ERROR in page/web.web.js from UglifyJs
Unexpected token: name (utilFunc) [page/web.web.js:2302,4]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 963 bytes [entry]
         + 1 hidden modules
webpack: Failed to compile.
