### ISSUE TITLE
能否用weex提供的playground预览此项目

### ISSUE THREAD

**Issue by lerit** [zwwill/yanxuan-weex-demo#9]
能否用weex提供的playground预览此项目呢，就是项目提供一个二维码，能够扫描快速在移动端使用playground预览项目效果，谢谢

**Comment by zwwill** [comment]
Weex的打包形式是单页多bundle的模式，所以只能调试单页，无法调试多页。
一下是首页二维码 IOS端，android暂未优化
![image](https://user-images.githubusercontent.com/20720117/30892410-39eddd7a-a2fe-11e7-8007-9acd2c9c52ab.png)

**Comment by lerit** [comment]
谢了！

**Comment by lerit** [comment]
非常好的项目
